"""empty message

Revision ID: 88069afd0f48
Revises: 451f6bd05a19
Create Date: 2019-08-01 20:55:52.928050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "88069afd0f48"
down_revision = "451f6bd05a19"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users_interests",
        sa.Column("interest_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["interest_id"], ["interests.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    )
    op.create_table(
        "projects_interests",
        sa.Column("interest_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["interest_id"], ["interests.id"]),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("projects_interests")
    op.drop_table("users_interests")
    op.drop_table("interests")
    # ### end Alembic commands ###
